version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: default
    ports:
      - "5432:5432"

  postgres-test:
    container_name: postgres-test
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: default
    ports:
      - "5433:5432"

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
    depends_on:
      - postgres
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../:/var/www
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./../:/var/www:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${CONFPATH}:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
  icertbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    #        - /home/sshadmin/project/letsencrypt:/var/www/certbot
    #        - /home/ubuntu/project/letsencrypt:/var/www/certbot
    #      networks:
    #        - frontend
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"